### PR TITLE
Audit fixes and cleanups to get query build rules

### PR DESCRIPTION
**Pull request by ramr**
@vurankar  PTAL thx.

Does anyone maintain this (since Brian left)? I noticed some npm audit issues that showed be in the agent.
Looks like this repo has not been touched for like 5 years. 

I did create this PR against the `master` branch as it is kind of irrelevant from a usage standpoint.
No one except the agent code uses this and even then the agent code uses the version published to `npmjs`. 

Added/fixed unit tests + added a lint tests. All those work fine.
Once this is tested (if we do do that!), could someone please do a `npm publish` to update the package @ 
https://www.npmjs.com/package/querybuilder-rules

I don't have the npms credentials to publish. Thx

### CODE REVIEW

**Review by krzysio94598 — APPROVED** [review]

**Comment by krzysio94598** [comment]
We really should just merge this repo into the `agent-zero` repo since that is the only place where it is used.

**Comment by vurankar** [comment]
@ramr Thanks!
@maryhowell do you have the npm credentials to publish this package ?

**Review by vurankar — APPROVED** [review]

**Comment by maryhowell** [comment]
@vurankar I do have the credentials. I will take a look. When do you need this?

**Comment by ramr** [comment]
thanks @krzysio94598 @vurankar 

@maryhowell  as re: timeline, whenever it is convenient for you. For now, I'll just use this repo for testing. Thx

**Comment by ramr** [comment]
> We really should just merge this repo into the `agent-zero` repo since that is the only place where it is used.

Sorry, my bad - I may have `misspoken` about the agent being the sole consumer. 
AFAICR, Brian originally used this as common code for the ui and agent, but am not sure if that's the case still.

I guess you can confirm if its using that npm module `querybuilder-rules` or this repo.

**Comment by krzysio94598** [comment]
@ramr I have looked in `unity` repo and there is no reference to this particular package. There is however a reference to the Meteor package that uses the original `bshamblen:jquery-querybuilder` package. That package has not been updated since May 2016! We need to start looking to some alternatives.

**Pull request merged**
